server:
  port: 80

spring:
  mail:
    port: 465
    host: smtp.qq.com
    username: 484201132@qq.com
    password: xxrqatlwqpxlbjjb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
