spring:
  mail:
    port: 465
    host: smtp.qq.com
    username: 484201132@qq.com
    password: xxrqatlwqpxlbjjb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  datasource:
    username: root
    password: 5e065db8d7d39ea1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.156.184:6548/broadcast_data_statistics_system?useSsl=true&serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatement=true
mybatis:
  mapper-locations: com/scfenzhi/mapper/*.xml
  type-aliases-package: com.scfenzhi.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    local-cache-scope: statement
